# Generated by Django 5.1.7 on 2025-04-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0003_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
